### ISSUE TITLE
Error while running subway.py

### ISSUE THREAD

**Issue by jaarizmendi** [lightalan/subwayclock#1]
I’ve been trying to run the subway.py

But I keep getting the same error message

pi@raspberrypi:~/subway $ ./subway.py
Traceback (most recent call last):
  File "./subway.py", line 171, in <module>
    m = Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1880, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

I don’t know if I’m missing something 

Thanks in advance

**Comment by lightalan** [comment]
Actually, this is one of those cases where the error message is quite
descriptive.

There is no display defined to open.

Try running x-terminal-emulator and see if a new terminal window for your
Pi opens on your PC, if it doesn't either xMing is not running and/or your
SSH client is not set for X11 forwarding.

**Comment by jaarizmendi** [comment]
I’ve been running this through an app from my Mac called Termius. Maybe that’s the problem. I gonna try use a VM with windows

Thanks

[ Sent from my iPhone XS Max ]

On Apr 5, 2019, at 9:10 PM, Alan Light <notifications@github.com<mailto:notifications@github.com>> wrote:

Actually, this is one of those cases where the error message is quite
descriptive.

There is no display defined to open.

Try running x-terminal-emulator and see if a new terminal window for your
Pi opens on your PC, if it doesn't either xMing is not running and/or your
SSH client is not set for X11 forwarding.

**Comment by jaarizmendi** [comment]
The issue was the app that I was using to run everything it didn’t have the screen functionality
