### ISSUE TITLE
Can't use 2 different station feeds in one instance...

### ISSUE THREAD

**Issue by RyokoAsakura** [lightalan/subwayclock#2]
If I try to use 2 different stations not on the same feed, the output fails. Example below.

`pi@raspberrypi:~/subway $ ./mta.py 234N A42N`
`(('2', '4', '4', '2', '4', '2', '4', '2', '4'), (4, 6, 15, 19, 22, 31, 39, 42, 54), [], [])`

`pi@raspberrypi:~/subway $ ./mta.py 234N 234S`
`(('2', '4', '4', '2', '4', '2', '4', '2', '2'), (3, 5, 14, 19, 22, 30, 39, 42, 54), ('2', '4', '4', '2', '2', '4', '4', '2', '4', '2', '4', '2', '4', '2', '2', '4', '2'), (7, 8, 17, 21, 30, 31, 34, 37, 46, 52, 58, 64, 71, 77, 91, 92, 107))`

I think you may end up having to make 2 calls if there are different feeds for the 2 stations called. 

I was using it for 2 nearby stations in Brooklyn headed into the city. One is Hoyt-Schermerhorn, on the A, C, G (A42N) and Nevins Street on the 2,3,4,5 (234N).

Thank you for your awesome code. It's working in ALL other aspects. 👍

**Comment by lightalan** [comment]
Hummm. I really had not anticipated that use case. I was assuming that it
would always be two directions at the same station.

This should be an easy fix.

Thanks.

**Comment by lightalan** [comment]
This has been fixed.
