### ISSUE TITLE
Stopped working this morning.

### ISSUE THREAD

**Issue by comawoo** [lightalan/subwayclock#3]
Everything was working and i was getting the correct times for my station, but starting this morning i noticed that the train time wasnt updating, and it stopped getting the train time. now when i try to run mta.py i get the following error. cant figure out why. 

> pi@raspberrypi:~/subway $ ./mta.py
> Traceback (most recent call last):
>   File "./mta.py", line 177, in <module>
>     print(getTrainTimes("Q03N","Q03S"))
>   File "./mta.py", line 148, in getTrainTimes
>     times = gettimes(f, ourUptownStation, ourDowntownStation)
>   File "./mta.py", line 73, in gettimes
>     feed.ParseFromString(response.content)
>   File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/message.py", line 187, in ParseFromString
>     return self.MergeFromString(serialized)
>   File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 1127, in MergeFromString
>     if self._InternalParse(serialized, 0, length) != length:
>   File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 1185, in InternalParse
>     new_pos = local_SkipField(buffer, old_pos, end, tag_bytes)
>   File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/decoder.py", line 1032, in SkipField
>     return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
>   File "/home/pi/.local/lib/python3.7/site-packages/google/protobuf/internal/decoder.py", line 922, in _SkipLengthDelimited
>     raise _DecodeError('Truncated message.')
> google.protobuf.message.DecodeError: Truncated message.
>

**Comment by lightalan** [comment]
The MTA API is now returning 'permission denied'
It's unclear why, but I sent them an email advising of what's going on.

**Comment by comawoo** [comment]
thank you.

**Comment by lightalan** [comment]
It seems to be working again now.
It looks like it was a transient problem on the MTA side.

**Comment by lightalan** [comment]
Transient MTA API issue.
