### ISSUE TITLE
subway.py not working tkinter import *

### ISSUE THREAD

**Issue by merryprankster02** [lightalan/subwayclock#6]
Im getting an error 

ModuleNotFoundError: No module named 'tkinter". I have no idea how to address this. 

I will state that i am doing this in an Ubuntu VM because my new PI and Display dont arrive until next week but i wanted to get everything working first so that this would be an easy build to give to my girlfriend as a gift. 

When i run ./mta.py with my station information i get good results so that script is working fine. 

Any help would be greatly appreciated.

thanks,
-mp

**Comment by lightalan** [comment]
Hummm. Try googling "installing Ubuntu tkinter"

**Comment by merryprankster02** [comment]
ok, i got that working and after making a few other tweaks to ubuntu and learning how to use the X11 options correctly in putty i now have this working perfectly for our L station. 

Now that I have this working it seems like this is barely touching the capabilities of the pi 4 and I was wondering is there any reason why this couldnt be run on a pi zero. Other than that, this is exactly what i wanted to make for her. The only thing that i may need to tweak a bit at this point is the display settings because i went with a different display than you but i wont know that until i try it.

**Comment by lightalan** [comment]
I've only tried it on a Pi 3+, which is probably way overkill for this from
a processing perspective. I don't see any reason why it would not work on a
Pi Zero (you would need to add WiFi, however).

Glad you got it working!
