### ISSUE TITLE
MTA sunsetting datamine.mta.info in favor of api.mta.info

### ISSUE THREAD

**Issue by penniesfromheaven** [lightalan/subwayclock#8]
Effective May 1, 2020, the MTA is shutting down datamine.mta.info, to which the script currently calls, in favor of using api.mta.info.

At a minimum, the feed number endpoints will need to change.

**Comment by lightalan** [comment]
Understood.
I'll be providing an be update.
Thanks.

**Comment by lightalan** [comment]
mta.py updated for new MTA API.
